In [1]:
import pandas as pd

# 데이터 불러오기
data = pd.read_csv('/Users/JooAnLee/mid_project/src/datasets/train250317-01_topic_merged.csv')
data.head()

,공고번호,주택명,공급지역코드,공급지역명,공급위치우편번호,공급위치,공급규모,모집공고일,청약접수시작일,청약접수종료일,...,전용면적당 시세차익,기사 번호,토픽 1,토픽 2,토픽 3,토픽 4,토픽 5,토픽 6,토픽 7,주요 토픽
0,2025000043,부천 JY 포에시아,410,경기,14636,경기도 부천시 원미구 신흥로 20,55,2025-02-28,2025-03-10,2025-03-11,...,NaN,1,0.002633,0.0026,0.0026,0.002633,0.361367,0.081,0.547233,토픽 7
1,2025000043,부천 JY 포에시아,410,경기,14636,경기도 부천시 원미구 신흥로 20,55,2025-02-28,2025-03-10,2025-03-11,...,NaN,1,0.002633,0.0026,0.0026,0.002633,0.361367,0.081,0.547233,토픽 7
2,2025000043,부천 JY 포에시아,410,경기,14636,경기도 부천시 원미구 신흥로 20,55,2025-02-28,2025-03-10,2025-03-11,...,NaN,1,0.002633,0.0026,0.0026,0.002633,0.361367,0.081,0.547233,토픽 7
3,2025000043,부천 JY 포에시아,410,경기,14636,경기도 부천시 원미구 신흥로 20,55,2025-02-28,2025-03-10,2025-03-11,...,NaN,1,0.002633,0.0026,0.0026,0.002633,0.361367,0.081,0.547233,토픽 7
4,2025000043,부천 JY 포에시아,410,경기,14636,경기도 부천시 원미구 신흥로 20,55,2025-02-28,2025-03-10,2025-03-11,...,NaN,1,0.002633,0.0026,0.0026,0.002633,0.361367,0.081,0.547233,토픽 7

In [2]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17250 entries, 0 to 17249
Data columns (total 50 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   공고번호               17250 non-null  int64
 1   주택명                17250 non-null  object
 2   공급지역코드             17250 non-null  int64
 3   공급지역명              17250 non-null  object
 4   공급위치우편번호           17250 non-null  int64
 5   공급위치               17250 non-null  object
 6   공급규모               17250 non-null  int64
 7   모집공고일              17250 non-null  object
 8   청약접수시작일            17250 non-null  object
 9   청약접수종료일            17250 non-null  object
 10  당첨자발표일             17250 non-null  object
 11  투기과열지구             17250 non-null  object
 12  조정대상지역             17250 non-null  object
 13  분양가상한제             17250 non-null  object
 14  정비사업               17250 non-null  object
 15  공공주택지구             17250 non-null  object
 16  대규모택지개발지구          17250 non-null  object
 17  수도권내민영공공주택지구       17250 non-null  object
 18  주택형                17250 non-null  object
 19  공급세대수              17250 non-null  int64
 20  순위                 17250 non-null  object
 21  거주지역               17250 non-null  object
 22  접수건수               17250 non-null  int64
 23  경쟁률                17250 non-null  float64
 24  최저당첨가점             17206 non-null  object
 25  최고당첨가점             17206 non-null  object
 26  평균당첨가점             17206 non-null  object
 27  전용면적               17250 non-null  int64
 28  평면유형               17250 non-null  object
 29  미달여부               17250 non-null  object
 30  공급금액(최고가 기준)       17250 non-null  float64
 31  위도                 17250 non-null  float64
 32  경도                 17250 non-null  float64
 33  행정동코드              15960 non-null  float64
 34  법정동코드              17250 non-null  float64
 35  시도                 17250 non-null  object
 36  시군구                17250 non-null  object
 37  읍면동1               15960 non-null  object
 38  읍면동2               17250 non-null  object
 39  전용면적당 공급금액(최고가기준)  17250 non-null  float64
 40  전용면적당 시세차익         14578 non-null  float64
 41  기사 번호              17250 non-null  int64
 42  토픽 1               17250 non-null  float64
 43  토픽 2               17250 non-null  float64
 44  토픽 3               17250 non-null  float64
 45  토픽 4               17250 non-null  float64
 46  토픽 5               17250 non-null  float64
 47  토픽 6               17250 non-null  float64
 48  토픽 7               17250 non-null  float64
 49  주요 토픽              17250 non-null  object
dtypes: float64(15), int64(8), object(27)
memory usage: 6.6+ MB