In [86]:
import pandas as pd

df = pd.read_csv("../storage/train_data/train-250312-01.csv", encoding="cp949")
df

,공고번호,주택명,공급지역코드,공급지역명,공급위치,공급규모,청약접수종료일,투기과열지구,조정대상지역,분양가상한제,...,거주지역,접수건수,경쟁률,최저당첨가점,평균당첨가점,최고당첨가점,전용면적,평면유형,미달여부,공급금액(최고가 기준)
0,2024000706,의왕 월암지구 대방 디에트르 레이크파크,410,경기,경기도 의왕시 월암동 공공주택지구 B2블록(경기도 의왕시 월암동 219-3일원),702,2025-01-02,N,N,Y,...,해당지역,13,0.54,0.0,0.00,0.0,75,A,Y,664170000.0
1,2024000706,의왕 월암지구 대방 디에트르 레이크파크,410,경기,경기도 의왕시 월암동 공공주택지구 B2블록(경기도 의왕시 월암동 219-3일원),702,2025-01-02,N,N,Y,...,기타지역,147,13.36,0.0,0.00,0.0,75,A,N,664170000.0
2,2024000706,의왕 월암지구 대방 디에트르 레이크파크,410,경기,경기도 의왕시 월암동 공공주택지구 B2블록(경기도 의왕시 월암동 219-3일원),702,2025-01-02,N,N,Y,...,해당지역,0,0.00,NaN,NaN,NaN,75,A,N,664170000.0
3,2024000706,의왕 월암지구 대방 디에트르 레이크파크,410,경기,경기도 의왕시 월암동 공공주택지구 B2블록(경기도 의왕시 월암동 219-3일원),702,2025-01-02,N,N,Y,...,기타지역,0,0.00,NaN,NaN,NaN,75,A,N,664170000.0
4,2024000706,의왕 월암지구 대방 디에트르 레이크파크,410,경기,경기도 의왕시 월암동 공공주택지구 B2블록(경기도 의왕시 월암동 219-3일원),702,2025-01-02,N,N,Y,...,해당지역,27,2.08,NaN,NaN,NaN,75,B,N,591150000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18855,2020000009,의왕 오전 동아루미체,410,경기,경기도 의왕시 전주남이길 23-26 (오전동),65,2020-02-19,N,N,N,...,기타지역,0,0.00,NaN,NaN,NaN,74,,N,NaN
18856,2020000009,의왕 오전 동아루미체,410,경기,경기도 의왕시 전주남이길 23-26 (오전동),65,2020-02-19,N,N,N,...,해당지역,16,0.73,23.0,31.36,51.0,74,,Y,NaN
18857,2020000009,의왕 오전 동아루미체,410,경기,경기도 의왕시 전주남이길 23-26 (오전동),65,2020-02-19,N,N,N,...,기타지역,138,23.00,23.0,31.36,51.0,74,,N,NaN
18858,2020000009,의왕 오전 동아루미체,410,경기,경기도 의왕시 전주남이길 23-26 (오전동),65,2020-02-19,N,N,N,...,해당지역,0,0.00,NaN,NaN,NaN,74,,N,NaN
18859,2020000009,의왕 오전 동아루미체,410,경기,경기도 의왕시 전주남이길 23-26 (오전동),65,2020-02-19,N,N,N,...,기타지역,0,0.00,NaN,NaN,NaN,74,,N,NaN

In [87]:
df.columns

Index(['공고번호', '주택명', '공급지역코드', '공급지역명', '공급위치', '공급규모', '청약접수종료일', '투기과열지구',
       '조정대상지역', '분양가상한제', '정비사업', '공공주택지구', '대규모택지개발지구', '수도권내민영공공주택지구',
       '신청자 30대 이하', '신청자 40대', '신청자 50대', '신청자 60대 이상', '당첨자 30대 이하',
       '당첨자 40대', '당첨자 50대', '당첨자 60대 이상', '주택형', '공급세대수', '순위', '거주코드',
       '거주지역', '접수건수', '경쟁률', '최저당첨가점', '평균당첨가점', '최고당첨가점', '전용면적', '평면유형',
       '미달여부', '공급금액(최고가 기준)'],
      dtype='object')

In [88]:
df['공급금액(최고가 기준)'] = df['공급금액(최고가 기준)'] / 10000
df['공급금액(최고가 기준)']

0        66417.0
1        66417.0
2        66417.0
3        66417.0
4        59115.0
          ...
18855        NaN
18856        NaN
18857        NaN
18858        NaN
18859        NaN
Name: 공급금액(최고가 기준), Length: 18860, dtype: float64

In [89]:
# 평당가격 칼럼 추가
df['평당가격'] = df['공급금액(최고가 기준)'] / df['전용면적']
df['평당가격']

0        885.56
1        885.56
2        885.56
3        885.56
4        788.20
          ...
18855       NaN
18856       NaN
18857       NaN
18858       NaN
18859       NaN
Name: 평당가격, Length: 18860, dtype: float64

In [90]:
dummy = pd.read_csv("C:/Users/user/mid-project/src/storage/raw_data/병합_청약매물_목록_정보 (서울, 경기, 인천)_위도경도추가_2.csv", encoding='cp949')

dummy.columns

Index(['공고번호', '주택명', '공급지역코드', '공급지역명', '공급위치우편번호', '공급위치', '공급규모', '청약접수종료일',
       '투기과열지구', '조정대상지역', '분양가상한제', '정비사업', '공공주택지구', '대규모택지개발지구',
       '수도권내민영공공주택지구', '신청자 30대 이하', '신청자 40대', '신청자 50대', '신청자 60대 이상',
       '당첨자 30대 이하', '당첨자 40대', '당첨자 50대', '당첨자 60대 이상', '주택형', '공급세대수', '순위',
       '거주코드', '거주지역', '접수건수', '경쟁률', '최저당첨가점', '평균당첨가점', '최고당첨가점', '전용면적',
       '평면유형', '미달여부', '위도', '경도', '시도', '시군구', '읍면동'],
      dtype='object')

In [91]:
dummy.head()

,공고번호,주택명,공급지역코드,공급지역명,공급위치우편번호,공급위치,공급규모,청약접수종료일,투기과열지구,조정대상지역,...,평균당첨가점,최고당첨가점,전용면적,평면유형,미달여부,위도,경도,시도,시군구,읍면동
0,2024000706,의왕 월암지구 대방 디에트르 레이크파크,410,경기,16107,경기도 의왕시 월암동 공공주택지구 B2블록(경기도 의왕시 월암동 219-3일원),702,2025-01-02,N,N,...,0.0,0.0,75,A,Y,37.309587,126.95639,경기도,의왕시,월암동
1,2024000706,의왕 월암지구 대방 디에트르 레이크파크,410,경기,16107,경기도 의왕시 월암동 공공주택지구 B2블록(경기도 의왕시 월암동 219-3일원),702,2025-01-02,N,N,...,0.0,0.0,75,A,N,37.309587,126.95639,경기도,의왕시,월암동
2,2024000706,의왕 월암지구 대방 디에트르 레이크파크,410,경기,16107,경기도 의왕시 월암동 공공주택지구 B2블록(경기도 의왕시 월암동 219-3일원),702,2025-01-02,N,N,...,NaN,NaN,75,A,N,37.309587,126.95639,경기도,의왕시,월암동
3,2024000706,의왕 월암지구 대방 디에트르 레이크파크,410,경기,16107,경기도 의왕시 월암동 공공주택지구 B2블록(경기도 의왕시 월암동 219-3일원),702,2025-01-02,N,N,...,NaN,NaN,75,A,N,37.309587,126.95639,경기도,의왕시,월암동
4,2024000706,의왕 월암지구 대방 디에트르 레이크파크,410,경기,16107,경기도 의왕시 월암동 공공주택지구 B2블록(경기도 의왕시 월암동 219-3일원),702,2025-01-02,N,N,...,NaN,NaN,75,B,N,37.309587,126.95639,경기도,의왕시,월암동

In [92]:
# 계약연도/계약월 칼럼 추가
dummy['계약연도'] = pd.to_datetime(dummy['청약접수종료일']).dt.year
dummy['계약월'] = pd.to_datetime(dummy['청약접수종료일']).dt.month

In [93]:
dummy = dummy[["공고번호", "주택명", "계약연도", "계약월", "공급지역명", "전용면적", "시군구", "읍면동"]]
dummy.head()

         공고번호                    주택명  계약연도  계약월 공급지역명  전용면적  시군구  읍면동
0  2024000706  의왕 월암지구 대방 디에트르 레이크파크  2025    1    경기    75  의왕시  월암동
1  2024000706  의왕 월암지구 대방 디에트르 레이크파크  2025    1    경기    75  의왕시  월암동
2  2024000706  의왕 월암지구 대방 디에트르 레이크파크  2025    1    경기    75  의왕시  월암동
3  2024000706  의왕 월암지구 대방 디에트르 레이크파크  2025    1    경기    75  의왕시  월암동
4  2024000706  의왕 월암지구 대방 디에트르 레이크파크  2025    1    경기    75  의왕시  월암동

In [95]:
dummy

             공고번호                    주택명  계약연도  계약월 공급지역명  전용면적  시군구    읍면동
0      2024000706  의왕 월암지구 대방 디에트르 레이크파크  2025    1    경기    75  의왕시    월암동
1      2024000706  의왕 월암지구 대방 디에트르 레이크파크  2025    1    경기    75  의왕시    월암동
2      2024000706  의왕 월암지구 대방 디에트르 레이크파크  2025    1    경기    75  의왕시    월암동
3      2024000706  의왕 월암지구 대방 디에트르 레이크파크  2025    1    경기    75  의왕시    월암동
4      2024000706  의왕 월암지구 대방 디에트르 레이크파크  2025    1    경기    75  의왕시    월암동
...           ...                    ...   ...  ...   ...   ...  ...    ...
18855  2020000009            의왕 오전 동아루미체  2020    2    경기    74  의왕시  전주남이길
18856  2020000009            의왕 오전 동아루미체  2020    2    경기    74  의왕시  전주남이길
18857  2020000009            의왕 오전 동아루미체  2020    2    경기    74  의왕시  전주남이길
18858  2020000009            의왕 오전 동아루미체  2020    2    경기    74  의왕시  전주남이길
18859  2020000009            의왕 오전 동아루미체  2020    2    경기    74  의왕시  전주남이길

[18860 rows x 8 columns]

In [96]:
dummy.drop_duplicates(subset=["공고번호"], keep='first')

,공고번호,주택명,계약연도,계약월,공급지역명,전용면적,시군구,읍면동
0,2024000706,의왕 월암지구 대방 디에트르 레이크파크,2025,1,경기,75,의왕시,월암동
28,2024000718,더샵 퍼스트월드,2024,12,서울,39,중랑구,상봉동
88,2024000712,의정부역 다채로움,2024,12,경기,84,의정부시,의정부동
96,2024000702,평택 브레인시티 수자인,2024,12,경기,59,평택시,평택브레인시티
108,2024000701,곤지암역 센트럴 아이파크,2024,12,경기,84,광주시,곤지암읍
...,...,...,...,...,...,...,...,...
18750,2020000060,위례신도시 A3-10BL 중흥S-클래스,2020,3,경기,101,하남시,위례순환로
18792,2020000086,구월 뷰그리안,2020,2,인천,56,남동구,구월로265번길
18796,2020000040,매교역 푸르지오 SK VIEW(수원),2020,2,경기,59,수원시,팔달구
18828,2020000010,양주옥정유림노르웨이숲,2020,2,경기,72,양주시,옥정동
18852,2020000009,의왕 오전 동아루미체,2020,2,경기,74,의왕시,전주남이길

In [94]:
df = df[['공고번호', '공급금액(최고가 기준)', '평당가격']]
df.head()

         공고번호  공급금액(최고가 기준)    평당가격
0  2024000706       66417.0  885.56
1  2024000706       66417.0  885.56
2  2024000706       66417.0  885.56
3  2024000706       66417.0  885.56
4  2024000706       59115.0  788.20

In [97]:
data = pd.merge(df, dummy.drop_duplicates(subset=["공고번호"], keep='first'), on='공고번호', how='inner')
data

,공고번호,공급금액(최고가 기준),평당가격,주택명,계약연도,계약월,공급지역명,전용면적,시군구,읍면동
0,2024000706,66417.0,885.56,의왕 월암지구 대방 디에트르 레이크파크,2025,1,경기,75,의왕시,월암동
1,2024000706,66417.0,885.56,의왕 월암지구 대방 디에트르 레이크파크,2025,1,경기,75,의왕시,월암동
2,2024000706,66417.0,885.56,의왕 월암지구 대방 디에트르 레이크파크,2025,1,경기,75,의왕시,월암동
3,2024000706,66417.0,885.56,의왕 월암지구 대방 디에트르 레이크파크,2025,1,경기,75,의왕시,월암동
4,2024000706,59115.0,788.20,의왕 월암지구 대방 디에트르 레이크파크,2025,1,경기,75,의왕시,월암동
...,...,...,...,...,...,...,...,...,...,...
18855,2020000009,NaN,NaN,의왕 오전 동아루미체,2020,2,경기,74,의왕시,전주남이길
18856,2020000009,NaN,NaN,의왕 오전 동아루미체,2020,2,경기,74,의왕시,전주남이길
18857,2020000009,NaN,NaN,의왕 오전 동아루미체,2020,2,경기,74,의왕시,전주남이길
18858,2020000009,NaN,NaN,의왕 오전 동아루미체,2020,2,경기,74,의왕시,전주남이길
18859,2020000009,NaN,NaN,의왕 오전 동아루미체,2020,2,경기,74,의왕시,전주남이길

In [98]:
# 칼럼명 변경 (공급금액_평당가격으로)
data.rename(columns={'평당가격': '공급금액_평당가격'}, inplace=True)

In [99]:
# 지역 동 별 평당가격
data.to_csv("./공급금액_평당가격.csv", index=False, encoding='cp949')
data

,공고번호,공급금액(최고가 기준),공급금액_평당가격,주택명,계약연도,계약월,공급지역명,전용면적,시군구,읍면동
0,2024000706,66417.0,885.56,의왕 월암지구 대방 디에트르 레이크파크,2025,1,경기,75,의왕시,월암동
1,2024000706,66417.0,885.56,의왕 월암지구 대방 디에트르 레이크파크,2025,1,경기,75,의왕시,월암동
2,2024000706,66417.0,885.56,의왕 월암지구 대방 디에트르 레이크파크,2025,1,경기,75,의왕시,월암동
3,2024000706,66417.0,885.56,의왕 월암지구 대방 디에트르 레이크파크,2025,1,경기,75,의왕시,월암동
4,2024000706,59115.0,788.20,의왕 월암지구 대방 디에트르 레이크파크,2025,1,경기,75,의왕시,월암동
...,...,...,...,...,...,...,...,...,...,...
18855,2020000009,NaN,NaN,의왕 오전 동아루미체,2020,2,경기,74,의왕시,전주남이길
18856,2020000009,NaN,NaN,의왕 오전 동아루미체,2020,2,경기,74,의왕시,전주남이길
18857,2020000009,NaN,NaN,의왕 오전 동아루미체,2020,2,경기,74,의왕시,전주남이길
18858,2020000009,NaN,NaN,의왕 오전 동아루미체,2020,2,경기,74,의왕시,전주남이길
18859,2020000009,NaN,NaN,의왕 오전 동아루미체,2020,2,경기,74,의왕시,전주남이길